### ISSUE TITLE
Crashes on startup 1.19

### ISSUE THREAD

**Issue by HOSEK1** [811Alex/NotifMod#1]
Quilt loader 0.17.0
Quilted Fabric API 2.0.0 Alpha 2
Cloth Config v6 7.0.72

MC version 1.19

**Comment by 811Alex** [comment]
Since there's no log, I'm assuming this is just an issue due to the differences in 1.19 and nothing else.
I just got done updating the mod to that, so give that a try!
_I haven't tried Quilt, so if you're still having issues with the latest version, it could be that, so in that case, feel free to open a new issue for it._
Enjoy!
