### ISSUE TITLE
RegEx filter

### ISSUE THREAD

**Issue by Romsmesme** [811Alex/NotifMod#11]
Hello! Kind of a newbie question as I'm a newbie myself!
I'm playing on a low pop server, and I wanna get sound notifications for all messages sent by players, as there are not a lot.
I've tried a few RegEx filters but couldn't find one that worked for me.

Thanks for your help (and your mod) !

**Comment by 811Alex** [comment]
Unless I'm mistaken, the defaults should do just that.

Do you happen to have any server plugins that change how the chat functions? Perhaps for formatting? There's a chance it's using the "game info" channel because of it.
The best way to figure this out is by enabling "Log message info", under "Chat Notifications" in NotifMod's settings and seeing what info NotifMod gives you for incoming player messages (the info will be in your logs).

If it _is_ using the "game info" channel, you'll have to make a regex to only get the player messages, according to how they're formatted in the server, since there's many other gameplay related things using that channel and it would get spammy, but I can help you with that, if you post the relevant info NotifMod gave you.

**Comment by Romsmesme** [comment]
Hi, thanks for the answer!
The plugins aren't publicly revealed, so I can't really tell.

Here is the log entry:
[20:37:06] [Render thread/INFO]: [System] [CHAT] [20:37:06] [G] <> wb
[20:37:06] [Render thread/INFO]: [NotifMod] Incoming non-matching message (game info, case-sens messages, case-insens mentions): [G] <PanicElf> wb

I believe the G stands for Global, as there is also a Local channel.
I don't really need the Local message notifications, but I don't mind having them neither !

**Comment by 811Alex** [comment]
No need to know the plugins, NotifMod's log setting gives enough info.

This is indeed in "game info", so here's a few options, assuming it's always a single letter in the brackets:
- To only get messages that start with [G]: `\[G\] .+`
- To get G or L: `\[[GL]\] .+`
- To get notifs for any capital letter: `\[[A-Z]\] .+`
- To do any single char: `\[.\] .+`
You can put any of those in the "game info" regex.

Also, if for example it can also be 1-3 letters, you can do something like: `\[[A-Z]{1,3}\] .+`
but allowing too many letters might make it so you get notifs from certain other plugins that print stuff in the [plugin name] format.

Hopefully this helps, feel free to let me know if not!

**Comment by Romsmesme** [comment]
This definitely helps, it works perfectly! Thanks a lot !!
