### ISSUE TITLE
Bug: Message/Mention Notifications in chat only working with 'game info'

### ISSUE THREAD

**Issue by heldheld** [811Alex/NotifMod#13]
I noticed that I only get the Message and Mention Notifications to work for public chat with the filter for 'game info' instead of 'chat', probably a bug?

**Comment by 811Alex** [comment]
This is most likely due to the server using a plugin to change the chat format. Some of those plugins will use that channel instead. Since it's server-side, NotifMod likely can't do much about this. You'd have to use a filter in "game info" that only lets player messages through, according to the server's formatting for that.

_If this does happen without server plugins, let me know, though._

Also, since I get a few reports about this, if anyone comes across this issue and knows what plugin their server uses that does that, I'd appreciate it if you could comment the name of the plugin here (if nobody else has already). It could be useful to have a few to test with, if I want to try and find some creative solution to this, at some point (no promises btw).
